sudo: false

language: node_js
node_js:
  - '12'

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - chromium-browser

cache:
  directories:
    - ./web/sd-ran-gui/node_modules

before_install:
  - cd web/sd-ran-gui

install:
  - npm install

before_script:
  - cd ../..

jobs:
  include:
    - stage: tests
      script:
        - make test
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./build/bin/push-images; fi'
