sudo: false

language: node_js
node_js:
  - '12'

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master

install:
  - npm install

jobs:
  include:
    - stage: tests
      script:
        - make build-gui
    